import {
  Leaf,
  Apple,
  Cherry,
  Grape,
  Milk,
  Droplets,
  Zap,
  Moon,
  Dumbbell,
  Shield,
  Heart,
  Sparkles,
  Flame,
  Sun,
  Star,
  Coffee,
  Cookie,
  Citrus,
  IceCream2,
  CupSoda,
  GlassWater,
  Salad,
  Egg,
  Flower,
  Wheat,
  Bean,
  Soup,
  Sandwich,
  Cake,
  Pizza,
  Candy,
  Croissant,
  Banana,
  Carrot,
  Nut,
  TreePalm,
  Snowflake,
  CloudRain,
  Waves,
  Mountain,
  Trees,
  Compass,
  Target,
  Trophy,
  Crown,
  Gem,
  Ribbon,
  Gift,
  Lightbulb,
  Clock,
  Timer,
  Gauge,
  Scale,
  Thermometer,
  Beaker,
  FlaskConical,
  Microscope,
  Pill,
  Syringe,
  Stethoscope,
  Activity,
  HeartPulse,
  Brain,
  Eye,
  Ear,
  Hand,
  Footprints,
  Baby,
  PersonStanding,
  Bike,
  Glasses,
  Paintbrush,
  Palette,
  Music,
  Camera,
  Film,
  BookOpen,
  PenLine,
  Pencil,
  Scissors,
  Hammer,
  Wrench,
  Plug,
  Wifi,
  Bluetooth,
  MapPin,
  Map,
  Home,
  Building,
  Tent,
  Armchair,
  Lamp,
  Fan,
  Umbrella,
  Bookmark,
  Menu,
  X,
  Link,
  Share2,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Search,
  ArrowDown,
  ArrowUp,
  Dices,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  leaf: Leaf,
  apple: Apple,
  cherry: Cherry,
  grape: Grape,
  milk: Milk,
  droplets: Droplets,
  zap: Zap,
  moon: Moon,
  dumbbell: Dumbbell,
  shield: Shield,
  heart: Heart,
  sparkles: Sparkles,
  flame: Flame,
  sun: Sun,
  star: Star,
  coffee: Coffee,
  cookie: Cookie,
  citrus: Citrus,
  'ice-cream': IceCream2,
  'cup-soda': CupSoda,
  'glass-water': GlassWater,
  salad: Salad,
  egg: Egg,
  flower: Flower,
  wheat: Wheat,
  bean: Bean,
  soup: Soup,
  sandwich: Sandwich,
  cake: Cake,
  pizza: Pizza,
  candy: Candy,
  croissant: Croissant,
  banana: Banana,
  carrot: Carrot,
  nut: Nut,
  'tree-palm': TreePalm,
  snowflake: Snowflake,
  'cloud-rain': CloudRain,
  waves: Waves,
  mountain: Mountain,
  trees: Trees,
  compass: Compass,
  target: Target,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  ribbon: Ribbon,
  gift: Gift,
  lightbulb: Lightbulb,
  clock: Clock,
  timer: Timer,
  gauge: Gauge,
  scale: Scale,
  thermometer: Thermometer,
  beaker: Beaker,
  'flask-conical': FlaskConical,
  microscope: Microscope,
  pill: Pill,
  syringe: Syringe,
  stethoscope: Stethoscope,
  activity: Activity,
  'heart-pulse': HeartPulse,
  brain: Brain,
  eye: Eye,
  ear: Ear,
  hand: Hand,
  footprints: Footprints,
  baby: Baby,
  'person-standing': PersonStanding,
  bike: Bike,
  glasses: Glasses,
  paintbrush: Paintbrush,
  palette: Palette,
  music: Music,
  camera: Camera,
  film: Film,
  'book-open': BookOpen,
  'pen-line': PenLine,
  pencil: Pencil,
  scissors: Scissors,
  hammer: Hammer,
  wrench: Wrench,
  plug: Plug,
  wifi: Wifi,
  bluetooth: Bluetooth,
  'map-pin': MapPin,
  map: Map,
  home: Home,
  building: Building,
  tent: Tent,
  armchair: Armchair,
  lamp: Lamp,
  fan: Fan,
  umbrella: Umbrella,
  bookmark: Bookmark,
  menu: Menu,
  x: X,
  link: Link,
  share: Share2,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  search: Search,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  dices: Dices,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] || Sparkles;
}

export { type LucideIcon };
